In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [3]:
(X_train,y_train),(X_test,y_test) = mnist.load_data()

In [4]:
X_train.shape

(60000, 28, 28)

In [5]:
X_train = X_train / 255.0

In [6]:
X_test = X_test / 255.0

In [7]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
y_train = to_categorical(y_train,10)
y_test = to_categorical(y_test,10)

In [9]:
y_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [10]:
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model

In [11]:
input_layer = Input(shape=(28,28,1))

In [12]:
flatten = Flatten()(input_layer)
layer_1 = Dense(128,activation='relu')(flatten)
output_layer = Dense(10,activation='softmax')(layer_1)

In [13]:
model = Model(inputs=input_layer,outputs=output_layer)

In [14]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['acc'])

In [15]:
model.fit(X_train,y_train,epochs=5,batch_size=32)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2603 - acc: 0.9259
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1152 - acc: 0.9658
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0805 - acc: 0.9762
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0604 - acc: 0.9814
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0466 - acc: 0.9855


In [16]:
test_loss, test_acc = model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.0793 - acc: 0.9766


In [17]:
print(test_acc)

0.9765999913215637


# Testing

In [18]:
import cv2 as cv
from tensorflow.keras.preprocessing.image import img_to_array

In [25]:
image = cv.imread('3.png',cv.IMREAD_GRAYSCALE)

In [26]:
image.shape

(452, 451)

In [27]:
image = cv.resize(image,(28,28))

In [28]:
image_input = img_to_array(image) / 255.0

In [29]:
pred = model.predict(image_input.reshape(1,28,28))

1/1 [==============================] - 0s 25ms/step


In [30]:
np.argmax(pred,axis=1)

array([3], dtype=int64)